### ISSUE TITLE
If I just want the F0?

### ISSUE THREAD

**Issue by ucasiggcas** [beiciliang/estimate-f0-inharmonicity#1]
Dear,

Thanks to your project.

But I have a question, the wav file you proposed is an isolated piano note,
and what does the **midiNum** mean?
`The midi number of the note in the given wav file`

Just a note in the wav, how many midi number? Not should be one? Why is 60?
Can't understand.

Could U help me, please ?
Thx

**Comment by beiciliang** [comment]
Hi,

I guess you misunderstood the sentence there. `midiNum` corresponds to a note name in the MIDI standard, e.g. midi number `60` is assigned to note `C4`. Please check [this article](https://newt.phys.unsw.edu.au/jw/notes.html) if you are still confused.

This info is needed since our repo implements the algorithm proposed in [this article](https://pdfs.semanticscholar.org/9355/3e7a1740d7f57d5a6d72508b82c542cebd35.pdf), which assumes that the played notes are known.

**Comment by ucasiggcas** [comment]
Thanks

But you may know crepe ,Pyin/yin or swipe,

These three algorithms do  not need the midiNum,

If I know the midiNum,just use cepstrum I can get the pitch.

**Comment by beiciliang** [comment]
The algorithms you mentioned focus on pitch estimation, while this repo is more towards piano acoustics. You may opt for different options based on which fits your project better :)
